site_name: Kae's Digital Garden & Programming Notebook
# theme: material
theme:
  name: material
repo_url: https://github.com/kaesluder/kae-garden-wiki
edit_uri: ""
plugins:
  - search
  - git-revision-date-localized
